### PR TITLE
NO-ISSUE: Change the name of DMN legacy editor to DMN classic editor

### PR DESCRIPTION
**Pull request by danielzhe**

### CODE REVIEW

**Comment by danielzhe** [comment]
@LightGuard

**Review by porcelli — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
fine for me, however, it is slightly unexpected, maybe it is just me, that sometimes we use `Classic` and sometimes we use `classic`.

**Review by kbowers-ibm — APPROVED** [review]

**Comment by danielzhe** [comment]
> fine for me, however, it is slightly unexpected, maybe it is just me, that sometimes we use `Classic` and sometimes we use `classic`.

I think it depends on the context.

**Comment by danielzhe** [comment]
Closed because the PR needs to target to another branch, not this one, as discussed in private chat....

**Pull request closed without merging**
