### PR TITLE
Fix docker run command for BAMOE Canvas

### PR DESCRIPTION
**Pull request by thiagoelg**
Environment variables should be set before the image name in the command: https://docs.docker.com/engine/reference/commandline/run/#usage

### CODE REVIEW

**Review by LightGuard — APPROVED** [review]
I'm good with how it is, however, are we going to be sticking with quay? Wondering if that image repo should be a variable.

**Comment by thiagoelg** [comment]
@LightGuard I don't have an answer for that :confused: 
If the image repo changes in the future there might be more things to change in the documentation.

**Comment by thiagoelg** [comment]
Yes! Should I open another PR cherry-picking this to 9.x?

**Comment by LightGuard** [comment]
@tiagobento Not sure why it isn't recognizing your approval as one of the ones necessary.

**Review by baldimir — APPROVED** [review]

**Pull request merged**
