### PR TITLE
License guide v1

### PR DESCRIPTION
**Pull request by kmacedovarela**
License guide based on available information as of July, 2024.  

- New section under introduction
- Navigation adjustment

Requires review and adjustments to match currently adopted docs patterns;

### CODE REVIEW

**Comment by kmacedovarela** [comment]
@justlmills 
Kindly review this proposed content and please recommend or implement adjustments to assure alignment with the existing code patterns.

@YajieY FYI

**Review by justlmills — APPROVED** [review]
I think this new section needs to be consolidated with the existing ILMT section https://www.ibm.com/docs/en/ibamoe/9.1.x?topic=installing-license-metric-tool-ilmt inside the release notes section similar to how it is done in the Cloud pak: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=notes-licenses-entitlements. It is probably easier to get your content in and consolidate and reorg afterwards

**Comment by kmacedovarela** [comment]
Good point. Note that the content structure is done differently on each product (https://www.ibm.com/docs/en/was-nd/9.0.5?topic=overview-licensing-guide). 

This is why i don't think this pr should be located under "release notes" section: 
- A section for release notes typically contains info covering updates and new features of a specific version. It's chronological and version-specific.  This license guide doesn't have these same characteristics. 

Despite my suggestions above, i'm willing to adjust the pr to match reviewers recommendations. 
lmk

**Comment by LightGuard** [comment]
@kmacedovarela Please make the change and I'll merge so we can get it into to the testing environment. If we need to iterate more, we can do that.

**Comment by kmacedovarela** [comment]
@LightGuard can you please confirm if it now meets the requirements?

**Comment by LightGuard** [comment]
Seems good

**Pull request merged**
