### PR TITLE
Update cors-proxy env variable name

### PR DESCRIPTION
**Pull request by ljmotta**

### CODE REVIEW

**Review by kbowers-ibm — APPROVED** [review]

**Comment by thiagoelg** [comment]
I believe more places need to be changed, basically everywhere that says `Git CORS Proxy` in some form should be changed.

The image URL (`https://quay.io/repository/bamoe/git-cors-proxy`), some deploy vars (`export APP_NAME_GIT_CORS_PROXY=bamoe-git-cors-proxy`), etc, all need updates.

What I don't know is if we change these values and names, will it reflect on the `9.0.x` docs as well? (it shouldn't! 9.0.x still uses Git CORS Proxy and should stay that way.)  @LightGuard help? :grimacing:

**Review by kbowers-ibm — CHANGES_REQUESTED** [review]
Updated Review: Sorry just realized this is targeting the main branch, whereas it needs to target the 9.1.x branch. As Thiago said, 9.0.1 still uses KIE_SANDBOX_GIT_CORS_PROXY_URL

**Comment by LightGuard** [comment]
Once we release, I'll merge 9.1.x back to main so it is current. If the 9.1.x PR contains the same info, let's close this one.

**Comment by ljmotta** [comment]
Closing this PR as the `main` will be updated with the 9.1.x branch

**Pull request closed without merging**
