### PR TITLE
Contributing guide

### PR DESCRIPTION
**Pull request by LightGuard**
This describes how to setup and us VS Code for contributions and also demonstrates the git workflow using VS Code.

### CODE REVIEW

**Comment by LightGuard** [comment]
Any chance someone could look this over and approve it? Been two weeks....

**Comment by veena-ux** [comment]
> Any chance someone could look this over and approve it? Been two weeks....

Jason, I need some time, I reviewing it currently.

**Review by porcelli — APPROVED** [review]
lgtm

**Comment by LightGuard** [comment]
@veena-ux have you been able to review this? Note, this won't be in the actual documentation, it's for anyone who wants to contribute to the docs.

**Pull request merged**
